implementação de header da aplicação e de componentes botão e links
ArthurRocha2100/drip-store-fs08 pull request #6
Opened 2024-02-16 22:58 UTC by ArthurRocha2100

Implementação de header e componentes

2024-02-17 01:09 UTC, dev-luismiguel requested changes
Ta muito massa a implementação!

Deixei umas sugestões

Verificar o bug do menu ficando abaixo dos componentes na pagina principal

2024-02-17 01:09 UTC, dev-luismiguel commented on src/App.tsx
>      </>
não é necessário o fragment

2024-02-17 01:09 UTC, dev-luismiguel commented on src/components/Header/Header.tsx
> +    )
```suggestion
    return isMobile ? <MobileHeader /> : <DesktopHeader />
```

2024-02-17 01:09 UTC, dev-luismiguel commented on src/components/Header/Header.tsx
> +    const [isVisible, setisVisible] = useState(false)
Como comentado em sala, refatorar para os 4 estados OPENING, OPENED, CLOSED, CLOSING

2024-02-17 01:10 UTC, dev-luismiguel reviewed
Utilizar props para componentes primarios e secundarios

2024-02-17 17:40 UTC, ArthurRocha2100 commented on src/components/Header/Header.tsx
> +    const [isVisible, setisVisible] = useState(false)
Implementação realizada, por favor, avaliar novamente o PR

2024-02-17 17:40 UTC, ArthurRocha2100 commented
Sujetões de correção e melhoria implementada implementadas.

2024-02-18 13:12 UTC, DevGarb approved these changes
Ao meu ver tudo ok 😅

2024-02-18 13:28 UTC, DevGarb commented on src/components/Header/components/NavBar/NavBar.tsx
> +                <TextLink to={ROUTES.MyProducts} onClick={onClick}>Meus Porodutos</TextLink>
Corrigir grafia "Categirias" e "Porodutos"

2024-02-20 00:15 UTC, ArthurRocha2100 commented on src/components/Header/components/NavBar/NavBar.tsx
> +                <TextLink to={ROUTES.MyProducts} onClick={onClick}>Meus Porodutos</TextLink>
Ajustado

2024-02-20 00:18 UTC, merged